.github/workflows/deploy.yaml
bin/resolve-latest-snapshot-tag

writes a github action that would deploy to staging every 12 hours

Writing a github action to deploy to staging

---

.github/workflows/deploy.yaml

This will show up in the badge on main repo, making it more descriptive.

Rename deploy workflow

---

bin/run-prober

https://github.com/civiform/civiform/pull/3187 added bin/bash as an entrypoint. removing extra from this file.

Remove bin/bash, it's not in the entrypoint

---

.github/workflows/aws-oidc-deploy-test.yaml
.github/workflows/azure-saml-ses-deploy-test.yaml
.github/workflows/build_push_image.yaml
bin/build-cloud-deployment

Will build new image on every push to main.

Add build action

---

.gitignore
cloud/shared/bin/deploy.py
cloud/shared/bin/destroy.py
cloud/shared/bin/run.py
cloud/shared/bin/setup.py
cloud/shared/bin/terraform.py

This now works:
cloud/shared/bin/run.py --command="terraform init"
cloud/shared/bin/run.py --command="terraform force-unlock LOCKID"

add ability to run terraform from run.py

---

.github/workflows/azure-saml-ses-deploy-test.yaml

Updated the secrets. 
Fixes https://github.com/civiform/civiform/issues/3505

Enable azure test

---

cloud/aws/templates/aws_oidc/variable_definitions.json

Underlying implementation was done in https://github.com/civiform/civiform/pull/3629

Add Auth0 as supported identity provider

---

.github/workflows/aws-oidc-deploy-test.yaml
.github/workflows/azure-saml-ses-deploy-test.yaml
cloud/shared/bin/run.py

Fixes https://github.com/civiform/civiform/issues/3692

Check tag for validity. Add "v" if needed

---

cloud/aws/bin/deploy.py
cloud/aws/bin/pgadmin.py
cloud/aws/templates/aws_oidc/bin/aws_cli.py
cloud/aws/templates/aws_oidc/bin/aws_template.py
cloud/aws/templates/aws_oidc/bin/destroy.py
cloud/aws/templates/aws_oidc/bin/setup.py
cloud/azure/templates/azure_saml_ses/bin/destroy.py
cloud/azure/templates/azure_saml_ses/bin/setup.py
cloud/shared/bin/doctor.py
cloud/shared/bin/lib/config_loader.py
cloud/shared/bin/lib/print.py
cloud/shared/bin/lib/setup_template.py
cloud/shared/bin/lib/terraform.py
cloud/shared/bin/run.py
cloud/shared/bin/setup.py

Fixes https://github.com/civiform/civiform/issues/3967.

Update print function to write to stderr

---

cloud/aws/templates/aws_oidc/app.tf

Tested: https://github.com/civiform/civiform/issues/4081#issuecomment-1402511987

Allow civiform task role to send SES emails from any identity

---

cloud/aws/templates/aws_oidc/app.tf
cloud/aws/templates/aws_oidc/variables.tf
cloud/azure/modules/app/locals.tf
cloud/azure/modules/app/variables.tf
cloud/azure/templates/azure_saml_ses/main.tf
cloud/azure/templates/azure_saml_ses/variables.tf
cloud/shared/variable_definitions.json

Feature flag for admin reporting UI.

Add reporting UI feature flag

---

cloud/aws/templates/aws_oidc/filestorage.tf

Attempts to fix https://github.com/civiform/civiform/issues/4697
Based on discussion in https://github.com/hashicorp/terraform-provider-aws/issues/22271

Add depends_on for log bucket ACLs

---

.github/workflows/push_monitoring_image.yaml

Small change to update the job name.

Update job name in monitoring github workflow

---

cloud/shared/bin/lib/config_loader.py

Fixes https://github.com/civiform/civiform/issues/5006

Use Python 3.5+ compatible dict syntax

---

cloud/aws/templates/aws_oidc/app.tf
cloud/aws/templates/aws_oidc/variable_definitions.json
cloud/aws/templates/aws_oidc/variables.tf

Related to: https://github.com/civiform/civiform/issues/5078

Add max and min ECS CPU threshold variables

---

cloud/aws/templates/aws_oidc/variable_definitions.json
cloud/aws/templates/aws_oidc/variables.tf

Related to: https://github.com/civiform/civiform/issues/5078
These can be used in app.tf once https://github.com/civiform/cloud-deploy-infra/pull/195 is submitted

Add additional ECS variables

---

cloud/aws/templates/aws_oidc/main.tf
cloud/aws/templates/aws_oidc/variable_definitions.json
cloud/aws/templates/aws_oidc/variables.tf

Related to: https://github.com/civiform/civiform/issues/5109

Add RDS alarms module

---

cloud/aws/templates/aws_oidc/app.tf
cloud/aws/templates/aws_oidc/variables.tf
cloud/shared/variable_definitions.json

Pass APPLICANT_REGISTER_URI and APPLICANT_PORTAL_NAME to server

---

cloud/aws/pgadmin/build-pgdmin

Fixes https://github.com/civiform/civiform/issues/5395

Add snapshots to pgadmin and make it consistent with other docker files

---

cloud/aws/pgadmin/pgadmin.Dockerfile

Seeing some updates with v7.6, so downgrading while I investigate further.

Update pgadmin version

---

cloud/aws/templates/aws_oidc/variable_definitions.json

https://github.com/civiform/civiform/issues/5601

Add m6g RDS instance class options

---

cloud/aws/templates/aws_oidc/app.tf
cloud/aws/templates/aws_oidc/variables.tf
cloud/shared/variable_definitions.json

Removing phone question type env. variable

Removing phone question type env. variable

---

cloud/aws/templates/aws_oidc/app.tf
cloud/aws/templates/aws_oidc/variable_definitions.json
cloud/aws/templates/aws_oidc/variables.tf
cloud/azure/modules/app/locals.tf
cloud/azure/modules/app/variables.tf
cloud/shared/bin/run.py
cloud/shared/variable_definitions.json

This reverts commit 01dba6c41de4cd5506dd99bddcc354ab2970807e.
With the removal of these vars, default values were behaving in unexpected ways. I'm reverting this until I can figure out what to do about default values.

Revert "Cleanup autogenerated server vars (#268)"

---

cloud/aws/templates/aws_oidc/app.tf
cloud/aws/templates/aws_oidc/filestorage.tf

This PR updates our terraform deploy scripts to create a new bucket called `"${var.app_prefix}-civiform-public-files-s3"` that will store the program images. This bucket allows any person to view the objects in any `program-summary-image/program-*` folder.
1) Run `bin/setup`.
2) On the local deploy:
1) Enable the PROGRAM_CARD_IMAGES flag.
2) As an admin, create a program then open the "Edit program image" page.
3) Upload an image and save it.
4) Verify that the program card preview shows your new image.
Follow the steps above, then:
1) As an admin, publish the program with the image.
2) Logout.
3) Verify that as an applicant, the programs homepage shows the image you uploaded as an admin.
1) Inside the AWS console for the dev site, upload an image that's **not** in a …

[Program Card Images] Add a new, publicly-accessible bucket to store program images.

---

cloud/aws/pgadmin/pgadmin.Dockerfile

Update pgadmin to latest version

Update pgadmin to latest version

---

cloud/aws/pgadmin/pgadmin.Dockerfile

Update to the latest version. I'm currently not able to access the pgadmin UI, so figured I'd try this. Weirdly our old version isn't listed on their site https://www.pgadmin.org/docs/pgadmin4/8.5/index.html
https://github.com/civiform/civiform/issues/7119

Update to latest pgadmin version

---

.github/workflows/aws-oidc-deploy-test.yaml
.github/workflows/e2e-test.yaml

Updating the dependency - this step is failing right now https://github.com/civiform/cloud-deploy-infra/actions/runs/9165684638/job/25199630695?pr=321

Update the aws-actions/configure-aws-credentials action to v4

---

cloud/aws/templates/aws_oidc/app.tf

This is for a test for Arkansas' deployment

Update health check

---

cloud/aws/modules/ecs_fargate_service/main.tf

This is for arkansas deployment

Update health check for aws_lb_target_group

---

cloud/aws/modules/ecs_fargate_service/main.tf

Please explain the changes you made here.

Make interval greater than timeout

---

cloud/aws/templates/aws_oidc/external_vpc.tf
cloud/aws/templates/aws_oidc/vpc.tf

This is related to [these failures](https://github.com/civiform/civiform-staging-deploy/actions/runs/9485251797/job/26136727247) after https://github.com/civiform/cloud-deploy-infra/pull/335
https://github.com/civiform/civiform/issues/7648

Remove legacy external_vpc references

---

e2e-test/civiform_config_aws_oidc.sh

Allow admin writeable in e2e-test

---

.github/workflows/aws-oidc-deploy-test.yaml
.github/workflows/e2e-test.yaml
.github/workflows/run_pytest.yaml

Updating some deprecated gh actions

Updating deprecated github actions

---

cloud/azure/templates/azure_saml_ses/variables.tf

This will fix the azure deployment
https://github.com/civiform/civiform/issues/9322

Add default for variable

---

cloud/aws/modules/ecs_fargate_service/main.tf

Listener should only be created after the security group rule is

This fixes an issue with the listener not being set up correctly

---

cloud/azure/bin/lib/bastion.sh
cloud/azure/modules/app/main.tf
cloud/azure/modules/bastion/main.tf
cloud/azure/modules/bastion/variables.tf

Added formatted name in one other place and added `/` around the regex so non-alphanumeric characters are removed.
Fixes https://github.com/civiform/civiform/issues/9153; https://github.com/civiform/civiform/issues/9418

Fix bastion vm name

---

cloud/shared/bin/run

Reverts civiform/cloud-deploy-infra#473
Automated deployments were failing.

Revert "Fix latest SHA lookup"

---

cloud/aws/bin/deploy.py
cloud/aws/bin/dumpdb.py
cloud/aws/bin/pgadmin.py
cloud/aws/bin/restoredb.py
cloud/shared/bin/lib/config_loader.py
cloud/shared/bin/rotate_app_secret.py
cloud/shared/bin/run.py
cloud/shared/bin/setup.py

Make sure that the user input we prompt for and accept in the process of interacting with the deploy system (setup, deploy, pgadmin, etc.) is consistent, case-insensitive and ignores whitespace.
Fixes #10948

Standardize yes/no inputs
