civiform/cloud-deploy-infra

- cloud/aws/templates/aws_oidc/monitoring.tf
Needed for Grafana to query metrics from prometheus
> Add aps:QueryMetrics to Grafana role permissions

- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/variables.tf
- cloud/shared/variable_definitions.json
That variable controls whether CiviForm can see applications for a given program. Feature already implemented in CiviForm but we don't propagated in AWS deployment scripts. So entities who use our deploy scripts can't set it.
> Pipe `ALLOW_CIVIFORM_ADMIN_ACCESS_PROGRAMS` in AWS deployment

- cloud/aws/templates/aws_oidc/variables.tf
Empty strings are propagated through environment variables to CiviForm and can override default values there. Usually we want to omit variables if they are not specified and having null as default helps with that.
> Set default string values to null instead of empty string

- cloud/cloud.Dockerfile
- cloud/shared/bin/doctor.py
The aws cli executable dynamically links against shared objects that are not included in alpine linux (build with musl instead of glibc).  Update the docker image to build from non-alpine varients.
Alternatives considered:
1. Adding gcompat to the apk add list.  This did not resolve the issue because aws-cli still linked against
missing shared objects.
1. Add missing shared objects manually like in
aws/aws-cli#4685 (comment).
This approached seems very brittle so I opted to use non-alpine
images instead.
Resolves https://github.com/civiform/civiform/issues/3508#issuecomment-1275373266.
1. `aws help` requires groff, switch the command to `aws --version`.
2. `aws configure list-profiles` does not work when only setting the AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY env variables.  Update …
> Update docker image to fix aws-cli, update doctor to properly report AWS info from within docker.

- cloud/aws/bin/pgadmin.py
- cloud/aws/bin/pgadmin_test.py
- cloud/shared/bin/run.py
During development, I accessed the pgadmin web UI from the same host that I was running the deploy tool on.  This is not the common scenario for our partners, however.  The deploy tool is more-often run from a shared VM.
Update the pgadmin command to be aware of this common use case:
- Explain why adding the IP of the host running the tool may still be useful.
- Print link to website to find public IP of host running the web browser. 
- Make the pgadmin service availability polling cancelled with user input.
> Do not assume the host running the deploy tool is the same host used to access pgadmin web UI

- cloud/aws/templates/aws_oidc/bin/setup.py
- cloud/azure/templates/azure_saml_ses/bin/setup.py
- cloud/shared/bin/setup.py
Without this change, setup has to be run twice because the initial terraform apply after setup fails due to known issue https://github.com/hashicorp/terraform-provider-aws/issues/19583. 
This change allows us to run bin/setup in an automated end-to-end test.
Fixes https://github.com/civiform/civiform/issues/3634
> Setup command can successfully run in a blank AWS account

- cloud/aws/templates/aws_oidc/monitoring.tf
This is needed to work around known issue https://github.com/hashicorp/terraform-provider-aws/issues/26111.
Users have not encountered this issue before because they have not removed CiviForm resources from their AWS account then re-deployed CiviForm.  Fixing this issue is required to run automated end-to-end tests in an AWS account.
Tested:
1. Ran bin/setup on an empty AWS account.  Setup and initial deployment succeeds.
2. Ran bin/deploy to ensure grafana workspace is not regenerated.  It is not because the random_id resource only changes if it has a `keepers` attribute specified: https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/id#keepers.
> Add random ID to managed grafana description

- cloud/aws/bin/deploy.py
- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/bin/aws_cli.py
- cloud/aws/templates/aws_oidc/bin/setup.py
By adding container healthchecks to civiform task definition, we can tell if the service is in the desired state by inspecting the service deployments.
Add code in bin/{setup,deploy} to wait for the service to reach desired state. Containers have to pass their healthchecks for the deployment to complete so this solves the "deploy tool completes without any error but the civiform container is crashlooping" issue.
Fixes https://github.com/civiform/civiform/issues/2845.
Fixes https://github.com/civiform/civiform/issues/3801.
> Add civiform container healthcheck, wait until service is healthy.

- .github/workflows/aws-oidc-deploy-test.yaml
- .github/workflows/e2e-test.yaml
Node16 is handled under a different tag. See https://github.com/aws-actions/configure-aws-credentials/issues/489
> Updating configure-aws-credentials action to use node16

- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/variables.tf
- cloud/shared/variable_definitions.json
This is a companion PR to https://github.com/civiform/civiform/pull/4171.
Tested:
1. Built a prod civiform image from https://github.com/civiform/civiform/pull/4171, pushed to docker.io/avritt/civiform:v0.0.1.
2. Added SHOW_CIVIFORM_IMAGE_TAG_ON_LANDING_PAGE=true to my civiform_config.sh file.
3. Updated the default for `civiform_image_repo` to `avritt/civiform` in cloud-deploy-infra/cloud/aws/templates/aws_oicd/variables.tf.
4. Deployed civiform to my test account.  Result:
> Support showing civiform version on landing page

- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/variables.tf
- cloud/shared/variable_definitions.json
Follow up to https://github.com/civiform/civiform/pull/4214.
Tested: deployed in my dev project with all new variables set to true:
> Support setting STAGING_ADD_NOINDEX_META_TAG, STAGING_DISABLE_DEMO_MODE_LOGINS, and STAGING_DISABLE_APPLICATION_GUEST_LOGIN in AWS

- .github/workflows/e2e-test.yaml
Most e2e failures (see https://github.com/civiform/civiform/issues/4034) have been due to a known issue with aws-nuke: https://github.com/rebuy-de/aws-nuke/issues/500.  There is a fix on its main branch but a new release has not been cut since 2022-12.  Re-running aws-nuke always resolves the issue.  This change mitigates the issue while we wait for the aws-nuke fix to be released.
Utilizes https://github.com/nick-fields/retry (no builtin retry config is provided by GitHub actions).
> Configure retries for e2e test post nuke step

- cloud/aws/templates/aws_oidc/app.tf
CIVIFORM_VERSION was added in https://github.com/civiform/civiform/pull/4405.  CIVIFORM_IMAGE_TAG is set in the prod.Dockerfile: https://github.com/civiform/civiform/blob/main/prod.Dockerfile#L46.
This change makes it so if CIVIFORM_VERSION in the civiform_config.sh file is set to "latest", the image tag (SNAPSHOT-3af89974-1678907834 for example) is show on the login page when SHOW_CIVIFORM_IMAGE_TAG_ON_LANDING_PAGE is enabled instead of "latest".  If CIVIFORM_VERSION is a release version like v1.18.0, only the release version is shown.
Fixes https://github.com/civiform/civiform/issues/4270.
Tested: Set CIVIFORM_VERSION to "latest" and deployed in my dev account, snapshot version is shown:
> Set CIVIFORM_VERSION instead of CIVIFORM_IMAGE_TAG

- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/variables.tf
- cloud/shared/variable_definitions.json
Part of https://github.com/civiform/civiform/issues/4380
Adds two env vars used by the common intake upsell page. See the linked issue for additional context.
> Add env vars for common intake

- cloud/aws/templates/aws_oidc/filestorage.tf
Attempts to fix https://github.com/civiform/civiform/issues/4697
Based on https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-object-ownership-simplify-access-management-data-s3/ and https://docs.aws.amazon.com/AmazonS3/latest/userguide/about-object-ownership.html
> Change civiform_files_ownership controls to BucketOwnerPreferred

- cloud/aws/templates/aws_oidc/main.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
Adds `POSTGRES_RESTORE_SNAPSHOT_IDENTIFIER` config var which can be used to destroy the replace the database with a new one restored from the specified snapshot.
The RDS instance has deletion protection on my default, requiring the deployer to access the AWS console and disable it before this can be used.
> Add ability to restore DB to snapshot

- cloud/aws/templates/aws_oidc/app.tf
Reverts civiform/cloud-deploy-infra#157
This caused the following errors
```
╷
│ Error: "name" cannot be longer than 32 characters
│ 
│   with module.ecs_fargate_service.module.ecs-alb[0].aws_lb_target_group.lb_https_tgs["default_http"],
│   on .terraform/modules/ecs_fargate_service.ecs-alb/main.tf line 166, in resource "aws_lb_target_group" "lb_https_tgs":
│  166:   name                          = "${var.name_prefix}-${each.key}-https-${each.value.target_group_port}"
│ 
╵
╷
│ Error: only alphanumeric characters and hyphens allowed in "name"
│ 
│   with module.ecs_fargate_service.module.ecs-alb[0].aws_lb_target_group.lb_https_tgs["default_http"],
│   on .terraform/modules/ecs_fargate_service.ecs-alb/main.tf line 166, in resource "aws_lb_target_group" "lb_https_tgs":
│  166:   name …
```
> Revert "Update Terraform cn-terraform/ecs-fargate-service/aws to v2.0.40"

- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/filestorage.tf
Followed instructions in https://github.com/hashicorp/terraform-provider-aws/issues/28353 to fix https://github.com/civiform/civiform/issues/4697
This PR also disables storage of load balancer logs on S3. The module we use for creating the fargate service has been setting up an S3 bucket for load balancer logs behind the scenes. We've never had need to view those logs, and don't have cloudwatch set up so that we could look at them without downloading and un-gzipping them directly from S3, which we've never done.
If we merge this PR with LB logs disabled, existing deployments will need to empty their LB log bucket before they'll be able to deploy again, otherwise terraform will fail with an error stating that it can't delete a non-empty bucket.
Alternatively, we could wait for this PR to …
> Set ownership controls on access log bucket

- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/variables.tf
- cloud/shared/validate_variable_definitions.py
- cloud/shared/variable_definitions.json
This PR pipes through the variables we need to enable Esri address correction in staging for AWS. Service area validation vars are not included here because they need to be sent through as arrays/lists which we don't have a pattern for yet (Issue to track that work is here: https://github.com/civiform/civiform/issues/4790). Eventually, we will need to include [all Esri vars](https://github.com/civiform/civiform/blob/fd0aaa002e2ee01d378ca90f236c316641ed0101/server/conf/application.conf#L722) in the deploy system.
Issue: https://github.com/civiform/civiform/issues/4621
Corresponding PR to add these to our AWS staging config file: https://github.com/civiform/civiform-staging-deploy/pull/47
> Add ESRI service to AWS staging

- cloud/aws/metrics/metrics_scraper.Dockerfile
- cloud/aws/metrics/otel-config.yaml
When the metrics scraper actions were moved into the infrastructure directory, the [otel-config file](https://github.com/civiform/civiform/blob/main/otel-config.yaml) wasn't brought over. Copied this over, so we can push the docker image with the config changes we made. I'll remove this file from the other directory as a follow up.
Here is the dockerfile that references this config: https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/aws/metrics/metrics_scraper.Dockerfile
Related to https://github.com/civiform/civiform/issues/4789
> Add otel-config file to infra metrics directory

- .github/workflows/push_monitoring_image.yaml
- cloud/aws/metrics/build-scraper
Add a github action to push the metrics scraper image
This is similar to https://github.com/civiform/cloud-deploy-infra/blob/main/.github/workflows/build_push_image.yaml
This also updates the metrics scraper docker image to add a tag when pushed for better versioning.
Related to fixing https://github.com/civiform/civiform/issues/4789
> Create github action to push metrics scraper

- cloud/shared/variable_definitions.json
There's another entry with the correct spelling. NONGATED_ELIGIBLITY_ENABLED vs. NONGATED_ELIGIBILITY_ENABLED
> Remove version of var that has a typo

- cloud/shared/bin/run
This pr fixes a couple of issues that were preventing this script from running:
1. there was a typo in the file path for `python_env_setup`
2. arguments were not being passed along to `run.py`
I tested this locally and confirmed the python package is downloaded and `run.py` successfully runs.
> fix file path and pass all args along to run.py

- cloud/shared/bin/lib/config_loader.py
`SKIP_CONFIRMATIONS` is a variable used by Terraform to know whether or not is should expect a "yes" before applying the terraform plan. 
In our [AWS staging deploy](https://github.com/civiform/civiform-staging-deploy/blob/2fe8d93dc1413724d451a7ce1d035c66c3bbe472/.github/workflows/aws_deploy.yaml#LL28C7-L28C25) (and likely other deployments) this is set to true so Terraform will not wait for a confirmation before applying the changes.
[This PR](https://github.com/civiform/cloud-deploy-infra/pull/132) updated several environment variables to be read from the config instead of `os.env`, including `SKIP_CONFIRMATIONS`. Merging this PR caused our staging deployment to fail with an error message that said `error asking for approval`. Some googling led me to understand this error is related to …
> fix SKIP_CONFIRMATIONS deploy bug

- cloud/aws/templates/aws_oidc/variables.tf
We removed the eligibility feature flag in https://github.com/civiform/civiform/pull/4879. This updates the description and setting of the variable in the deploy infra repo. I'll plan to remove this variable in a couple of weeks.
Related to: https://github.com/civiform/civiform/issues/4605
> Update description and setting of eligibility flag

- cloud/shared/bin/env-var-docs-python-dependencies.txt
- cloud/shared/bin/run
Now that [we have logic](https://github.com/civiform/cloud-deploy-infra/pull/154) to pull in the correct version of `env-var-docs.json` for the version of CiviForm being deployed, we need to make sure we're pulling in the correct version of the parser package as well.
This change adds logic to the `run` script to fetch the correct version of the parser package via the Github api based on the version of CiviForm being deployed.
I tested it locally by deploying with different versions (v1.24.0 and "latest") and confirming that different versions of the parser packaged were downloaded.
> download correct version of parser package for civiform version

- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
- cloud/shared/variable_definitions.json
Allow configuration of ECS task CPU and memory
https://github.com/civiform/civiform/issues/5058
> Add ECS task CPU and memory variables

- cloud/aws/templates/aws_oidc/app.tf
This includes using the following:
- max_cpu_evaluation_period
- min_cpu_evaluation_period
- max_cpu_period
- min_cpu_period 
- scale_target_max_capacity
- scale_target_min_capacity
Related to: https://github.com/civiform/civiform/issues/5078
> Use new ECS variables

- cloud/aws/templates/aws_oidc/main.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
Add additional configuration variables for AWS RDS alarms.
Related to: https://github.com/civiform/civiform/issues/5109
> Add threshold variables for RDS alarms

- cloud/aws/templates/aws_oidc/main.tf
- cloud/aws/templates/aws_oidc/variables.tf
Turn off RDS alarms by default while investigating a warning in terraform
> Default RDS alarms to false

- cloud/shared/bin/run
Currently, snapshot parsing is failing on staging due to different flag options for the `grep` command. This PR refactors the snapshot tag parsing to be done by [Docker's `--format` option](https://docs.docker.com/engine/reference/commandline/inspect/#options) + Go templating to make it system agnostic.
Also added a couple of log lines for help debugging.
I tested this locally and on staging and it works in both environments.
> Use docker --format to parse snapshot from "latest" tag

- cloud/shared/bin/run.py
Once we are ready to start using the new system of auto-generating server vars, we can merge this to overwrite the calls to [run.py](https://github.com/civiform/civiform-deploy/blob/9f277338e676b7d8a2b27795a51cbdc83c69f703/bin/lib/checkout.sh#L68) in local copies of `civiform-deploy` with calls to [bin/run](https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/shared/bin/run).
The first time a CE deploys after this change is merged, their local code will be updated to call the new `run` script with the updated arguments. The time they deploy after that, their deployment will use the new path with auto-generated server vars.
Note: I had to add a check for if the env is Github Actions to get tests to pass. We should make sure folks aren't deploying via Github Actions (like we are …
> Turn server var autogeneration on for all

- cloud/shared/bin/run.py
A CE ran into problems with python versioning when deploying with [this change](https://github.com/civiform/cloud-deploy-infra/pull/185). This PR reverts the change so CEs will go back to using the older version of the deploy code (without server var autogeneration).
> turn off run script

- cloud/shared/bin/run
Adds some validations and error handling for the run script. Handles:
Fixes https://github.com/civiform/civiform/issues/5140
> Validations and error messages for run script

- cloud/aws/templates/aws_oidc/bin/aws_cli.py
end 2 end tests have been failing for the past week: https://github.com/civiform/cloud-deploy-infra/actions/workflows/e2e-test.yaml
The error message is 
```ERROR: service did not become healthy in expected amount of time. This usually means the new tasks are crash-looping, but can mean the check timed out before the service finished starting.```
Doubling the number of status check tries before failure will let us know if it's a timeout issue or an actual failure and we need to dig deeper.
> bump num tries before timeout

- cloud/aws/templates/aws_oidc/alarms.tf
- cloud/aws/templates/aws_oidc/main.tf
- cloud/aws/templates/aws_oidc/variables.tf
This removes the warning that items have been updated outside of terraform, in addition to allowing for more configurability by having the setup of these alarms in our repo.
Many of these alarms were brought over from https://github.com/lorenzoaiello/terraform-aws-rds-alarms
I've turned on some by default based on the [proposal](https://docs.google.com/document/d/17fQ063Bde1016zdZIsa777OIKgky4qnvqWgzW7qbeIY/edit#heading=h.ph56eiunik55)
The only two that I still need to add are connection_count_anomalous and maximum_used_transaction_ids_too_high, but I need to add some extra variables for those, so I'll do that in a separate PR.
[#5078](https://github.com/civiform/civiform/issues/5078)
> Add remaining variables for RDS alarms and enable some by default

- cloud/shared/bin/lib/config_loader.py
The work being done in [this pr](https://github.com/civiform/civiform/pull/5246) will make it so that values for `ADMIN_WRITEABLE` vars are set via the admin settings panel and not in the config. This pr updates the deploy system code to ignore the "required" value if the mode is `ADMIN_WRITEABLE` so that deploys will pass without requiring those settings in the config file.
> Add check for ADMIN_WRITEABLE to required var check for var autogeneration

- cloud/shared/bin/run.py
Once [this pr](https://github.com/civiform/civiform/pull/5298) is merged, server var auto-generation will work on older versions of python which will unblock AR's use of it.
> turn on server var autogeneration

- cloud/shared/variable_definitions.json
These will be removed in a few weeks when we fully commit to server var autogeneration. In the meantime this allows them to be omitted in the config file.
> Make admin-writeable variables optional

- cloud/aws/templates/aws_oidc/variables.tf
Seattle was seeing these alarms go off in their staging instance. We should default to smaller thresholds.
> Update RDS alarm thresholds

- cloud/shared/bin/run.py
Fixes the CLI prompt for confirming a non-release tag to not print a newline before the user's input
Previous behavior:
> No newline before CLI input

- cloud/aws/pgadmin/build-pgdmin
When trying to run this file, we'd get the error 
`./build-pgdmin: bad interpreter: /usr/bin/bash: no such file or directory`
Tested and this fixes it.
> Fix pgadmin bash

- .github/workflows/push_pgadmin_image.yaml
Fixes https://github.com/civiform/civiform/issues/5399
> Add github action for pushing pgadmin image

- cloud/aws/modules/pgadmin/main.tf
- cloud/aws/modules/pgadmin/task.tf
Enabling execute mode allows us to ssh into the pgadmin ECS task to run commands, such as pg_restore with more customized flags.
See [doc](https://docs.google.com/document/d/1sdkCUf3ViPmPmY0ltWrGOmlPJuY_HIaV4L2fxphPGoU/edit#heading=h.qwl4b729kpja) for more details on full pg restore steps that were used.
Related to https://github.com/civiform/civiform/issues/5447
> Enable execute for pgadmin ECS task

- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/bin/resources.py
- cloud/aws/templates/aws_oidc/bin/setup.py
- cloud/aws/templates/aws_oidc/secrets.tf
Add new AWS secrets for admin OIDC.
There is one new AWS secret for the admin OIDC client id and one new AWS secret for the admin OIDC client secret.
> Add new AWS secrets for admin OIDC

- cloud/aws/templates/aws_oidc/main.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
This allows these advanced database monitoring tools to be enabled through terraform.
By default they will be turned off.
https://github.com/civiform/civiform/issues/5605
> Allow RDS performance insights and advanced monitoring to be enabled

- cloud/aws/templates/aws_oidc/variables.tf
Update the env var docs to document the default state for STAGING_ADD_NOINDEX_META_TAG
Related to https://github.com/civiform/civiform/issues/5635
> Document that the no index meta tag is false by default

- cloud/aws/templates/aws_oidc/alarms.tf
We should have the app prefix with the sns ID, so there aren't issues with different environments
> Environmentalize email sns topic

- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/monitoring.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
- cloud/shared/bin/lib/terraform.py
Adds a variable that controls whether or not to create Prometheus and Grafana instances in AWS. This is intended to be used for staging environments where the deployer doesn't want monitoring and would like to save on the expense.
Tested: ran `bin/deploy` for an existing deployment which reported that existing prometheus and grafana resources are moved i.e. not destroyed and replaced:
```
resource "aws_grafana_workspace" "CiviForm_metrics" {
id                        = "g-866ca756db"
name                      = "cf-test-civiform-metrics"
tags                      = {}
}
resource "aws_prometheus_workspace" "metrics" {
id                  = "ws-4caf9bf0-89c9-4047-8239-6cca617f4621"
tags                = {}
}
```
> Add variable to disable monitoring stack

- cloud/shared/bin/run
Allows deployment of images with tags of the form `DEV-[short sha]-[branch name]`
> Allow deploying DEV images

- cloud/aws/modules/ecs_fargate_service/outputs.tf
- cloud/aws/templates/aws_oidc/alarms.tf
- cloud/aws/templates/aws_oidc/modules.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
- cloud/shared/bin/lib/terraform.py
Add an alarm to check if the MemoryUtilization metric is above a threshold (default 80%).
[Cloudwatch metrics](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cloudwatch-metrics.html)
> add high memory utilization alarm

- cloud/shared/bin/lib/config_loader.py
Allows deployment of images with tags of the form `DEV-[short sha]-[branch name]`
> Resolve commits from dev image tags

- .github/workflows/push_monitoring_image.yaml
I'm getting an [error](https://github.com/civiform/cloud-deploy-infra/actions/runs/7131087493/job/19418919745) when trying to push the monitoring image from a branch. I noticed we cd into a directory that doesn't exist in the cloud-deploy-infra repo. Trying to remove that directory to see if that fixes the issue.
> Fix github action to push image

- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
Add variables for container memory and memory reservation (for the server container and scraper container)
This also includes a validation to ensure we don't allow invalid variable values.
https://github.com/civiform/civiform/issues/3421
This is what one of the error messages look like on failure:
```
╷
│ Error: Module output value precondition failed
│ 
│   on variables.tf line 339, in output "validate_container_memory":
│  339:     condition     = var.ecs_server_container_memory + var.ecs_metrics_scraper_container_memory <= var.ecs_task_memory
│     ├────────────────
│     │ var.ecs_metrics_scraper_container_memory is 2048
│     │ var.ecs_server_container_memory is 4097
│     │ var.ecs_task_memory is 6144
│ 
│ The ECS_SERVER_CONTAINER_MEMORY + ECS_METRICS_SCRAPER_CONTAINER_MEMORY must
│ …
```
> Add variables for container memory and memory reservation

- cloud/aws/modules/pgadmin/main.tf
AWS load balancer name can't be longer than 32 characters. https://docs.aws.amazon.com/elasticloadbalancing/latest/application/create-application-load-balancer.html#configure-load-balancer
```
│ Error: "name" cannot be longer than 32 characters
│ 
│   with module.pgadmin[0].aws_lb_target_group.pgadmin,
│   on ../../modules/pgadmin/main.tf line 29, in resource "aws_lb_target_group" "pgadmin":
│   29:   name        = local.name_prefix
│ 
```
> trim aws load balancer name to 32 characters (max size)

- cloud/aws/bin/pgadmin.py
https://github.com/civiform/cloud-deploy-infra/pull/283 shortened civiform to "cf", but did not correct other uses.
> correct pgadmin prefix for secrets to reflect app name

- cloud/aws/templates/aws_oidc/secrets.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
https://github.com/civiform/civiform/issues/6506
We want to create a terraform variable for the random password length, so certain deployments can update it before they have users.
We'll need to update this before the play framework migration (https://www.playframework.com/documentation/2.9.x/Migration29#Application-Secret-enforces-a-minimum-length), and it will be easier to change the length for the deployments without many users now.
> Create terraform variable for secret length

- cloud/aws/templates/aws_oidc/bin/setup.py
- cloud/shared/bin/lib/config_loader.py
- cloud/shared/bin/run
This PR cleans up remaining todos and comments in the deploy code related to server variable autogeneration: https://github.com/civiform/civiform/issues/4612
I also removed a TODO related to a closed issue: https://github.com/civiform/civiform/issues/3116
Part of: https://github.com/civiform/civiform/issues/5250
> Remove todos related to server var autogeneration

- cloud/azure/templates/azure_saml_ses/main.tf
- cloud/azure/templates/azure_saml_ses/variables.tf
- cloud/deploys/dev_azure/civiform_config.example.sh
- e2e-test/civiform_config_aws_oidc.sh
With the introduction of server variable autogeneration, the names for variables used in the deploy system must match those in `env-var-docs.json`. Furthermore, vars that are `ADMIN_WRITABLE` shouldn't be set in the deploy system at all. This PR does some additional cleanup for these types of variables that was missed the first time around.
1. Remove `ADMIN_WRITEABLE` vars from Azure files.
2. Rename vars in the end to end test so they match server vars
Related to #6636
> Remove and rename admin writeable vars

- .github/workflows/aws-oidc-deploy-test.yaml
The url now requires an authorization token to fetch the staging config. I added it to secrets and referenced it here. 
Fixes https://github.com/civiform/civiform/issues/7011
> Replace url for staging config

- .github/workflows/aws-oidc-deploy-test.yaml
- .github/workflows/azure-saml-ses-deploy-test.yaml
- cloud/shared/bin/destroy_backend_state_resources.py
- cloud/shared/bin/run.py
- cloud/shared/bin/setup.py
This change will make it so that the `bin/setup` script can be re-run without error. It adds a call to `terraform destroy` when backend resources are detected so that those are destroyed before deleting the Terraform state tracking resources. It also updates the feedback to the user to make it clear that:
1) They should allow the script to run to completion to avoid issues with partially created backend state
2) Destroying the backend resources is destructive and should be run with caution 
Updated documentation: https://github.com/civiform/docs/pull/415
1. Run `bin/setup` and allow the script to run to completion
2. Run `bin/setup` again and answer "yes" to all the prompts. Existing resources should be destroyed and the setup should succeed.
Fixes …
> Destroy previously created resources before re-running bin/setup

- e2e-test/nuke.yaml
End to end tests have been failing because of the new role that was added that cannot be deleted. This PR filters this role out of the nuke config to allow the test to pass.
Fixes https://github.com/civiform/civiform/issues/7084
> filter out new SSO role

- cloud/aws/templates/aws_oidc/bin/resources.py
`bin/setup` is currently throwing an error because AWS is unable to find the secret named `esri_arcgis_api_token_secret`. That's because it needs to be pre-pended with `civiform` which is set [here](https://github.com/civiform/cloud-deploy-infra/blob/bdbc123b92387eecd54e85d7837531da8c24794b/cloud/aws/templates/aws_oidc/secrets.tf#L214C29-L214C79). This pr fixes that.
Run `bin/setup` from this branch.
Fixes https://github.com/civiform/civiform/issues/7407
> Fix esri secret setting

- cloud/shared/bin/lib/config_loader.py
- cloud/shared/bin/lib/config_loader_test.py
Variables that are marked as `ADMIN_WRITEABLE` in [env-var-docs.json](https://github.com/civiform/civiform/blob/main/server/conf/env-var-docs.json) are editable in the admin settings config and should not be set in the deploy configs. This change adds an error if an `ADMIN_WRITEABLE` is found in the deploy config. It also allows the ability to override this by setting `ALLOW_ADMIN_WRITEABLE=true` in the deploy config.
Notes:
- Need to check all of the config files we manage to see if we need to add `ALLOW_ADMIN_WRITEABLE=true` (I know we need to do this for staging)
- Need to update documentation
- Need to provide guidance to CEs that they might see this error if they have `ADMIN_WRITEABLE` vars in their deploy config
1. Add an admin writeable variable to your deploy config (Eg. …
> Throw error if ADMIN_WRITEABLE vars in config

- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
- cloud/aws/templates/aws_oidc/vpc.tf
This PR allows the external vpc related configs to be set from the `civiform_config.sh` script.
> Allow setting the external vpc related variables from config script.

- cloud/shared/validate_variable_definitions.py
- cloud/shared/validate_variable_definitions_test.py
Add support for list type, since we want to add a variable for private and public subnets, which will be a list of strings
This will be used to support a list of public and private subnets from Charlotte (https://github.com/civiform/civiform/issues/7648)
Fixes https://github.com/civiform/civiform/issues/7750
> Add list type to acceptable variable definition types

- cloud/shared/bin/lib/config_loader_test.py
- cloud/shared/bin/lib/write_tfvars.py
Add support for list type, since we want to add a variable for private and public subnets, which will be a list of strings
This is a simpler way of doing it than https://github.com/civiform/cloud-deploy-infra/pull/338, but this version does it based on implied type, instead of looking at the type inputed within the variables file.
This is a follow up to https://github.com/civiform/cloud-deploy-infra/pull/337
If we don't do this, we get an error when we add `export EXTERNAL_VPC_PRIVATE_SUBNET_IDS=["test"]` to the config:
```
│ Error: Invalid value for input variable
│ 
│   on setup.auto.tfvars line 14:
│   14: external_vpc_private_subnet_ids="['test']"
│ 
│ The given value is not suitable for var.external_vpc_private_subnet_ids
│ declared at variables.tf:523,1-43: list of string required. …
```
> Add support for terraform list variables with implied list type

- cloud/aws/modules/ecs_fargate_service/outputs.tf
- cloud/aws/templates/aws_oidc/main.tf
If the VPC is managed outside of terraform, we need to ensure that the tasks have access to the database to make connections. 
This will set up an ingress if the VPC is managed outside of terraform. This was needed as part of the charlotte deployment - https://github.com/civiform/civiform/issues/7648
Here is what the change looks like in the UI - https://github.com/civiform/civiform/issues/7648#issuecomment-2189083230
Tested by deploying in the charlotte test environment with the config from this [branch](https://github.com/civiform/civiform-staging-deploy/compare/main...clt-changes) and tested to ensure this didn't change anything in an existing environment
https://github.com/civiform/civiform/issues/7648
> Ensure the tasks have access to the database to make connections if using non-terraform VPC

- cloud/aws/modules/ecs_fargate_service/main.tf
- cloud/aws/modules/ecs_fargate_service/variables.tf
- cloud/aws/templates/aws_oidc/app.tf
If we don't do this, we get an error:
```
│ Error: creating ELBv2 application Load Balancer (charlotte-vpc10-civiform-lb): InvalidSubnet: VPC vpc-0f18a363a62cc1675 has no internet gateway
│       status code: 400, request id: f09051a2-e2fe-4b4d-9bc5-c80ba8f2d009
│ 
│   with module.ecs_fargate_service.aws_lb.civiform_lb,
│   on ../../modules/ecs_fargate_service/[main.tf](http://main.tf/) line 26, in resource "aws_lb" "civiform_lb":
│   26: resource "aws_lb" "civiform_lb" {
```
This is needed for Charlotte's deployment. We could also decide to make this a separate variable from the vpc changes, or can do that in the future if they no longer should be tied together.
Tested by deploying in the charlotte test environment with the config from this …
> Make load balancer internal when vpc is not managed through CiviForm

- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/vpc.tf
Use new list of subnet IDs and also fix the VPC count. Tested on charlotte test environment and this doesn't change anything for existing deployments
Tested by deploying in the charlotte test environment with the config from this [branch](https://github.com/civiform/civiform-staging-deploy/compare/main...clt-changes) and tested to ensure this didn't change anything in an existing environment
https://github.com/civiform/civiform/issues/7648
> Fix vpc count for check and use list of subnet IDs

- cloud/azure/templates/azure_saml_ses/main.tf
- cloud/azure/templates/azure_saml_ses/variables.tf
Remove obsolete feature flags from the Azure terraform templates
None of these exist in env-var-docs.json anymore so they are dead.
> Remove dead feature flags from azure terraform templates

- cloud/aws/modules/ecs_fargate_service/main.tf
- cloud/aws/modules/ecs_fargate_service/variables.tf
- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
Add an option to enable ELB access logging.
- Deploy normally w/o the new setting
- Update `civiform_config.sh` and set `LB_LOGGING_ENABLED="true"`
- Redeploy and observe the access logging is enabled.
Part of https://github.com/civiform/civiform/issues/6726
> Add an option to enable ELB access logging

- cloud/aws/modules/ecs_fargate_service/main.tf
- cloud/aws/modules/ecs_fargate_service/variables.tf
- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
Charlotte's deployment with a custom VPC was successful, but their load balancers weren't able to make requests. Adding the inbound rule manually fixed this, so adding to the terraform config as well.
This is set up as a variable and if it isn't specified it won't be created.
Tested by setting up without the rule then added it through terraform and saw it represented in the same way that charlotte has it:
Fixes https://github.com/civiform/civiform/issues/7648
> Add inbound rule for Charlotte deployment

- cloud/azure/bin/lib/key_vault.sh
Use url safe charset for postgres password. Section 2.3 of https://www.ietf.org/rfc/rfc3986.txt states that url safe is `Characters that are allowed in a URI, but do not have a reserved purpose, are called unreserved. These include uppercase and lowercase letters, decimal digits, hyphen, period, underscore, and tilde.`
- [x ] Added the correct label
- [ x] Assigned to a specific person or `civiform/deployment-system` 
- [x ] Created tests which fail without the change (if possible)
- [x ] Performed manual testing (at a minimum run `bin/setup` without your changes and then `bin/deploy` with your changes to ensure your changes don't break existing deployments)
- [ x] Extended the README / documentation, if necessary
> Generate url safe password for postgres database

- cloud/aws/templates/aws_oidc/main.tf
We were getting an error when running pgadmin:
```
╷
│ Error: Invalid value for input variable
│ 
│   on main.tf line 169, in module "pgadmin":
│  169:   subnet_ids      = local.vpc_private_subnets
│ 
│ The given value is not suitable for module.pgadmin[0].var.subnet_ids
│ declared at ../../modules/pgadmin/variables.tf:47,1-22: element 0: string
│ required.
```
By pointing at the ID variable instead, we are successfully able to create pgadmin resources. Note: this doesn't change anything for non-vpc enabled deployments, since _private_subnets and _private_subnet_ids point to the same thing for those https://github.com/civiform/cloud-deploy-infra/blob/d5c99d3a9f34c32b9626089e243a7f86950ecb7e/cloud/aws/templates/aws_oidc/vpc.tf#L19
https://github.com/civiform/civiform/issues/8412
> Fix pgadmin for deployment with vpc

- .github/workflows/e2e-test.yaml
Per https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#schedule we have to actually make a commit here now that Avritt has left in order to keep this going and have the workflow run as this user.
> Update e2e test schedule

- cloud/azure/modules/app/role-assignments.tf
"Users" cannot read / write to the keyvault, which worked okay locally I think because there were other permissions in play from using az login but the deployment yaml runs the terraform process using the service-principal id of the app registration, which requires Administrator access  in order to perform the required keyvault actions during deployment. 
- [ x] Added the correct label
- [ x] Assigned to a specific person or `civiform/deployment-system` 
- [ x] Created tests which fail without the change (if possible)
- [ x] Performed manual testing (at a minimum run `bin/setup` without your changes and then `bin/deploy` with your changes to ensure your changes don't break existing deployments)
- [x ] Extended the README / documentation, if necessary
If instructions are needed for manual …
> Change role profile of the keyvault to "Administrator" from "User" 

- cloud/azure/modules/app/file-storage.tf
- cloud/azure/modules/app/logs.tf
- cloud/azure/templates/azure_saml_ses/main.tf
- change `retention_duration` to use new name `operational_default_retention_duration` 
- `enforce_private_link_endpoint_network_policies` can be safely removed because private link is not currently set up 
- retention_policy can be safely removed due to [this stackoverflow comment](https://stackoverflow.com/questions/77717130/retention-policy-terraform-is-deprecated-inside-azurerm-monitor-diagnostic-setti) stating that `enabled_log` blocks use the retention policy set in the `azurerm_log_analytics_workspace` resource. 
- [ x] Added the correct label
- [x ] Assigned to a specific person or `civiform/deployment-system` 
- [ x] Created tests which fail without the change (if possible)
- [ x] Performed manual testing (at a minimum run `bin/setup` without your changes and then `bin/deploy` …
> Update azurerm version to 4.1.0 and remove outdated dependencies 

- cloud/azure/modules/app/locals.tf
- cloud/azure/modules/bastion/main.tf
- cloud/azure/templates/azure_saml_ses/providers.tf
- cloud/azure/templates/azure_saml_ses/variables.tf
- providers need to include subscription id. This error didn't appear during my testing of the 4.1.0 update because it only occurs when the deployment setup changes.
- change private-ip allocation method to "Static"
- the staging resource uses a standard SKU and "dynamic" allocation is only permissible for more expensive plans. It looks like "Static" just reserves an IP address and doesn't change it, not that I see a reason to change it after it's allocated. 
- remove `DOCKER_REGISTRY_SERVER_URL` 
- this is now deprecated. The now preferred way of doing it is to set it in the linux_web_app resource, [which we are already doing](https://github.com/civiform/cloud-deploy-infra/blob/main/cloud/azure/modules/app/main.tf#L76). 
allocation_method = "Static" 
- [x ] Added the correct label
- [x ] …
> Minor v4.1.0 azurerm bugfixes

- .github/workflows/run_pytest.yaml
This allows one to run `pytest` in the root folder to trigger all the tests, instead of needing to modify PYTHONPATH environment variable.
Local test passes:
```
(venv) ych@penguin ~/git/cloud-deploy-infra (git)-[pytest-fix]-
$ pytest 
=================================== test session starts ===================================
platform linux -- Python 3.11.2, pytest-8.3.2, pluggy-1.5.0
rootdir: /home/ych/git/cloud-deploy-infra
collected 59 items                                                                        
cloud/aws/bin/pgadmin_test.py ..................                                    [ 30%]
cloud/shared/bin/lib/check_test.py .                                                [ 32%]
cloud/shared/bin/lib/config_loader_test.py ...............                          [ 57%] …
```
> Add `__init__.py` files to convert the folders to python module.

- cloud/azure/modules/app/main.tf
We don't need this resource because we have the virtual_network_subnet_id set in the app resource.
- [x ] Added the correct label
- [x ] Assigned to a specific person or `civiform/deployment-system` 
- [x ] Created tests which fail without the change (if possible)
- [ x] Performed manual testing (at a minimum run `bin/setup` without your changes and then `bin/deploy` with your changes to ensure your changes don't break existing deployments)
- [x ] Extended the README / documentation, if necessary
> Remove unnecessary azurerm_app_service_virtual_network_swift_connection resource

- cloud/shared/bin/python_env_setup
- cloud/shared/bin/run
Charlotte had a new firewall rule installed, which caused an error during deployment: `SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate`.
With this PR, we now allow a cert file to be specified. This also involved a change in their deployment repo, similar to [this](https://github.com/civiform/civiform-deploy/compare/clt-python?expand=1).
Charlotte tested this change and it fixed their issue and allowed them to deploy successfully.
https://github.com/civiform/civiform/issues/8943
> Allow an optional cert file to be specified that gets used by pip

- cloud/azure/main.tf
- cloud/azure/templates/azure_saml_ses/providers.tf
- cloud/azure/templates/azure_saml_ses/variable_definitions.json
- cloud/azure/templates/azure_saml_ses/variables.tf
Only affects AZURE deployments.
Will configure the azurerm TF provider to skip_provider_registrations when the variable AZURE_SKIP_PROVIDER_REGISTRATION is set to "true".
The variable is defaulted to "false" and set as optional.
Tested by deploying onto azure.
Ran the azure deployment script. -- Documentation for AZURE deployments is in progress.
> Add ability to skip provider registrations for the terraform azure provider.

- cloud/azure/main.tf
We're having an issue with skip_provider_registration. This azure provider is different than https://github.com/civiform/cloud-deploy-infra/blob/c569edf4b4e8ea21ecf0cb776419a996efe9d5d5/cloud/azure/templates/azure_saml_ses/main.tf#L9, so updating for consistency
Also, Miami Dade is having issues that seem related to https://github.com/hashicorp/terraform-provider-azurerm/issues/27466, which should be fixed in the more recent versions of azurerm
https://github.com/civiform/civiform/issues/9153
> Upgrade azure provider version

- cloud/azure/modules/app/locals.tf
Will be submitted after PR https://github.com/civiform/civiform/pull/9234  is merged.
That PR changes the name of the azure container env var for private files.
> Update azure env var AZURE_STORAGE_ACCOUNT_CONTAINER  to AZURE_STORAGE_ACCOUNT_CONTAINER_NAME

- cloud/aws/templates/aws_oidc/variables.tf
- cloud/azure/templates/azure_saml_ses/variables.tf
- cloud/shared/variable_definitions.json
This will be used so we can conditionally create AWS resources based on this variable (see https://github.com/civiform/cloud-deploy-infra/pull/420)
I think for azure we'll eventually use graph-api as the default, but since that isn't supported, I left it empty for now
https://github.com/civiform/civiform/issues/9258
> Create variable for email provider

- cloud/azure/modules/app/file-storage.tf
- cloud/azure/modules/app/locals.tf
Adds resource creation of the public-files container for program card images in Azure.
Tested manually by deploying to Azure and verifying that a public-files container exists in the default storage-account.
Civiform can't write these files yet, so that testing will be done when the functionality is added to Civiform.
> Have Terraform create the public-files container for program card images for Azure deployments

- cloud/shared/bin/setup.py
Compare responses in low string, like we do in most other places.
> call lower() on a user response before comparing to 'y' or 'yes'

- cloud/azure/templates/azure_saml_ses/providers.tf
the subscription id is needed in, and should be retrieved from the environment variable.
> Reference the environment variable for AZURE subscription ID

- cloud/azure/templates/azure_saml_ses/variable_definitions.json
- cloud/azure/templates/azure_saml_ses/variables.tf
Prior fix to add a reference to subscription neglected to add the tf var definition.
This fixes that problem, and has been tested in an azure deployment.
> azure_subscription needs to be defined as a TF var before its referenced.

- .github/workflows/e2e-test.yaml
- e2e-test/nuke.yaml
The e2e test has been failing because of the recent upgrade to `slack-github-action@v2` and needed updates to the nuke.yaml. This PR fixes those things and successfully runs the e2e test when manually running the action. The action has been failing in recent weeks as an "Unknown Event" (https://github.com/civiform/cloud-deploy-infra/actions/runs/12577039084) so we'll have to see tonight if it successfully runs on the cron.
> fix e2e test

- cloud/aws/modules/ecs_fargate_service/main.tf
- cloud/aws/modules/ecs_fargate_service/variables.tf
- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
This is a change to allow the port 80 listener to be disabled. It defaults to enabled, which means nothing would change for existing deployments
Tested on an existing deployment and see the message:
```
- resource "aws_lb_listener" "lb_http_listeners" {
- arn               = "arn:aws:elasticloadbalancing:us-east-1:484539786037:listener/app/civiform-eng-civiform-lb/81602ccf4c6d6e67/b20038124635f3d2" -> null
- id                = "arn:aws:elasticloadbalancing:us-east-1:484539786037:listener/app/civiform-eng-civiform-lb/81602ccf4c6d6e67/b20038124635f3d2" -> null
- load_balancer_arn = "arn:aws:elasticloadbalancing:us-east-1:484539786037:loadbalancer/app/civiform-eng-civiform-lb/81602ccf4c6d6e67" -> null
- port              = 80 -> null
- protocol          = "HTTP" -> null
- tags …
```
> Allow port 80 listener to be disabled

- cloud/aws/modules/ecs_fargate_service/main.tf
There was an issue finding the resource, since with the "count", the resource is [0]. See error:
Error: waiting for ELBv2 Listener (arn:aws:elasticloadbalancing:us-west-2:405662711265:listener/app/cf-test-civiform-lb/24d38790082d292e/b7ba689fcd4e2743) create: couldn't find resource
│ 
│   with module.ecs_fargate_service.aws_lb_listener.lb_http_listeners[0],
│   on ../../modules/ecs_fargate_service/main.tf line 195, in resource "aws_lb_listener" "lb_http_listeners":
│  195: resource "aws_lb_listener" "lb_http_listeners" {
│ 
╵
I've validated a successful deployment after this change:
```
Terraform will perform the following actions:
- resource "aws_lb_listener" "lb_http_listeners" {
- arn               = "arn:aws:elasticloadbalancing:us-east-1:145023101365:listener/app/ns-civiform-lb/8b2328 …
```
> Update listener and listener rule to fix deployment

- cloud/azure/modules/app/main.tf
- cloud/azure/modules/app/variables.tf
This PR adds the `civiform/civiform` prefix that was missing from the docker image when deploying with Azure. It follows the same pattern we use for [AWS deploys](https://github.com/civiform/cloud-deploy-infra/blob/65157756919dd750424137f66ab4e8458ed139af/cloud/aws/templates/aws_oidc/app.tf#L37).
I tested this by deploying with Azure locally and making sure the deployment succeeded with the correct image.
Deploy Azure using this branch
Fixes https://github.com/civiform/civiform/issues/9343
> Fix name of docker image for azure

- cloud/azure/modules/bastion/main.tf
Miami Dade got the following error when doing a deployment:
```
Error: unable to assume default computer name "computer_name" cannot contain the special characters: `\/"[]:|<>+=;,?*@&~!#$%^()_{}'` Please adjust the "name", or specify an explicit "computer_name"
│
│   with module.app.module.bastion.azurerm_linux_virtual_machine.bastion_vm,
│   on ../../modules/bastion/main.tf line 73, in resource "azurerm_linux_virtual_machine" "bastion_vm":
│   73: resource "azurerm_linux_virtual_machine" "bastion_vm" {
```
https://github.com/civiform/civiform/issues/9153
> Shorten resource group name and strip non-alphanumeric characters

- cloud/azure/bin/lib/bastion.sh
Still getting the error:
│ Error: unable to assume default computer name "computer_name" cannot contain the special characters: `\/"[]:|<>+=;,?*@&~!#$%^()_{}'` Please adjust the "name", or specify an explicit "computer_name"
Realized this was another place we set the bastion name.
> Create a helper function to get the formatted name for bastion

- cloud/aws/bin/pgadmin.py
- cloud/aws/modules/pgadmin/main.tf
- cloud/aws/modules/pgadmin/variables.tf
- cloud/aws/templates/aws_oidc/app.tf
- cloud/aws/templates/aws_oidc/main.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
This reverts commit b992f874413500dbd72492f13cf5ed445d0133fc.
We think that TLS1.3 is the source of the timeout issue so reverting for now.
> Revert "Change default LB policy (#450)"

- cloud/aws/modules/ecs_fargate_service/main.tf
- cloud/aws/templates/aws_oidc/app.tf
Currently the `/playIndex` is being used as the healthcheck endpoint on AWS ECS tasks. This endpoint doesn't make any database calls so if the database is in a bad state the healthcheck is just like `tra la la, I'm happy and ok skipping in a park of daisies`.
Switching to using the `/programs` endpoint for now. This should let the task report a bad state so AWS will kill it and spin up another.
> Changing AWS healthcheck path to '/programs'

- cloud/aws/bin/deploy.py
This PR re-enables allowing deployments to restore the db to a db snapshot on deploy (not just on setup). It adds a user input check to help guard against data loss from accidentally deploying with this value set.
1. Spin up a deployment and seed the database. Publish all programs.
2. Take a snapshot of the db in AWS
3. Clear the database via the developer tools
4. Set `export POSTGRES_RESTORE_SNAPSHOT_IDENTIFIER=<snapshot name>` in your deployment config
5. Run `bin/deploy` and follow the prompts
6. Deployment should succeed and you should see data re-populated on your site again
Slack thread with context: https://civiform.slack.com/archives/C044VUMJSSH/p1746624121481959
> Enable restoring from a snapshot on deploy

- cloud/aws/bin/deploy.py
- cloud/aws/templates/aws_oidc/main.tf
- cloud/aws/templates/aws_oidc/variable_definitions.json
- cloud/aws/templates/aws_oidc/variables.tf
This PR adds a configurable variable `delete_automated_backups` that controls whether or not system/auto-generated snapshots will be deleted when the associated db is destroyed. We default this to `false` to override Terraform's default which automatically deletes system snapshots when the associated db is torn down. We allow this variable to be configurable so admin can allow system snapshots to be deleted if they want to.
We decided to make this change after attempting to restore a gov environment to a system snapshot only to have it deleted in the process.
Note: Manual snapshots are not deleted when the db is destroyed and are not affected by this change.
I tested this in the following ways:
- `bin/setup` …
> Turn off delete_automated_backups

- cloud/shared/bin/lib/terraform.sh
Removing `-json` allows the Azure terraform deploy to be interactive and prevents the need for setting `export SKIP_CONFIRMATIONS=true`.
Setup an Azure deployment instance. Deploy to that instance and confirm the deploy is interactive in the terminal and that it deploys successfully.
Related to https://github.com/civiform/civiform/issues/8894
> Make azure deploy interactive

- cloud/azure/bin/setup_tf_shared_state
Deploys with complex resource group names (names with non-alphanumeric characters, eg. `rocky_fine`) were failing because we now format resource group names to remove non-alphanumeric characters (eg. `rocky_fine` -> `rockyfine`) and use the formatted name to create resources. However, the deploy script was using the original resource group name instead of the formatted group name to check for the existence of the storage account, resulting in the existing storage account not being recognized and the deploy attempting to create a new storage account only to fail because one already existed in that resource group.
Note: This was not causing the deploy to fail on staging, because the original resource group name (`staging`) happens to only contain alphabetic characters and therefore matches …
> Fix azure resource group name in deploy

- cloud/azure/bin/deploy
In https://github.com/civiform/cloud-deploy-infra/pull/457 we fixed the image tag so it's carried through during setup, but deploy remained broken. This PR fixes the Azure deploy flow so image tag is carried through there as well. 
`IMAGE_TAG` is an outdated var name that is no longer set in our config. `TF_VAR_image_tag` is now the var that is used to reference the image tag that is derived from the `CIVIFORM_VERSION` config var.
Setup an instance in Azure then deploy to that same instance and make sure the correct image tag shows up in Azure under the app service properties and that the site loads.
Related to https://github.com/civiform/civiform/issues/8894
> Carry Docker image tag through Azure deploy

- cloud/azure/bin/setup-keyvault
- cloud/azure/modules/app/locals.tf
- cloud/azure/modules/app/main.tf
- cloud/azure/modules/app/secrets.tf
- cloud/azure/templates/azure_saml_ses/main.tf
Azure applicant authentication wasn't working and part of the reason was because the server config values weren't being passed through to azure. Ensured this works as expected by deploying azure staging and logging in.
Since we are picking up the config values, the discovery URI doesn't need to be set within the deployment, which was needed prior.
Deployed to staging with changes https://staging-azure.civiform.dev/
Fixes https://github.com/civiform/civiform/issues/9785
> Fix Azure applicant auth and ensure config values get set correctly

- .github/workflows/push_deployment_env_image.yaml
We no longer have windows deployers and this is no longer succeeding, so disabling this for now. It is still available for workflow dispatch and we can re-enable it if it is needed in the future. 
> Disable deployment env image

- cloud/aws/modules/ecs_fargate_service/main.tf
- cloud/aws/modules/ecs_fargate_service/variables.tf
- cloud/aws/templates/aws_oidc/app.tf
This change wires the alert SNS topic ARN (civiform_alert_topic) into the ECS autoscaling module so that scaling alarms also trigger email alerts. This ensures that alarms tied to ECS CPU thresholds are surfaced alongside existing system alerts.
This PR updates the `app.tf` configuration to pass the shared `civiform_alert_topic` ARN into the ECS autoscaling module via the `sns_topic_arn` input. Previously, ECS CPU utilization alarms existed solely for autoscaling and did not notify the alert topic. With this change:
- ECS autoscaling alarms now publish to the same SNS topic used for system-wide alerts.
- Notification emails (e.g., low CPU) are delivered to the same endpoint configured in `civiform_alert_email`.
No changes were required in the `alarms.tf` module, as the topic was already …
> feat: route ECS autoscaling CloudWatch alarms to civiform_alert SNS topic

- cloud/aws/templates/aws_oidc/app.tf
The coalesce function was still failing because of this null setting 
Fix issue with coalesce - https://github.com/civiform/cloud-deploy-infra/actions/runs/17482750501/job/49656236476#step:11:3562
> Update another null check

- cloud/aws/modules/ecs_fargate_service/main.tf
I created a change in the autoscaling module that adds a new variable specifically for scale up events https://github.com/cn-terraform/terraform-aws-ecs-service-autoscaling/pull/41. Scale down events have been really noisy, so this allows us to specifically notify on scale up.
Tested and saw that this only created an alarm for autoscaling up not down. 
https://github.com/civiform/civiform/issues/11269
> Use new variable to only notify on scale up events
